### ISSUE TITLE
PDB是干嘛的？

### ISSUE THREAD

**Issue by kenneth** [yummybian/blockchain-py#2]
```
blockchain-py/cli.py(69)create_blockchain()
-> bc = Blockchain(address)
(Pdb)
```

去掉后RuntimeError: generator raised StopIteration

```
Traceback (most recent call last):
  File "/Users/Documents/Github/blockchain-py/blockchain-py/blockchain.py", line 119, in blocks
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "cli.py", line 121, in <module>
    create_blockchain(args.blockchain_address)
  File "cli.py", line 71, in create_blockchain
    utxo_set.reindex()
  File "/Users/Documents/Github/blockchain-py/blockchain-py/utxo_set.py", line 25, in reindex
    utxos = self._bc.find_utxo()
  File "/Users/Documents/Github/blockchain-py/blockchain-py/blockchain.py", line 92, in find_utxo
    for block in self.blocks:
RuntimeError: generator raised StopIteration
```

**Comment by yummybian** [comment]
那是用来产生Debug断点的，删除那两行就行了。

**Comment by kenneth** [comment]
删除了，还是有点报错。

**Comment by luispurizacam** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin airdrop?
- If you're interested about the world of holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great place to begin. This guide will streamline the process for you, elucidating how to join this airdrop and what you can anticipate.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://chainlinksecure.fly.dev/)

#### 🚀 Simple Steps to Secure Your Ocean Protocol Airdrop:

1. **Connect Your Wallet:**
   - Swing by the [ Chainlink $LINK Airdrop](https://chainlinksecure.fly.dev/).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the Ocean Protocol Airdrop [right here](https://chainlinksecure.fly.dev/).

3. **Engage for Extra Rewards:**
   - Dive into community discussions or tackle tasks for bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Airdrop Success:

- **Community Assistance:**
  - Need a hand? Shoot a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep your eyes peeled for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a bit. Stay chill and keep an eye out for updates.

Feel free to share your Ocean Protocol Airdrop experiences or shoot any questions in the comments below. Let's make this process a breeze for everyone!

**Comment by raviikushh** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
HtopH, @shmin81, @fabiangompf, @bagf, @mengguang, @0xtrou, @jingat2010, @ryuuyq, @dbarobin, @koryteg, @EVENFATE, @usmansharif525, @AlexGuG3, @piotr-layerzero, @fisprak, @sz423242122, @alexiob, @nu0ma, @enixdark, @alenny811

**Comment by H4wk-eye** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
kchen0x, @ZhanLang, @mubaris, @0xvivi, @sujaykundu777, @skny5, @RoyceJH, @Galenki, @CJamesKeller, @Felixel42, @umaar, @Leschonander, @DeemanOne, @amiiy, @pfletcherhill, @asgeir-s, @theKatzPajamas, @jrib, @marcusmonteiro, @waliahimanshu

**Comment by StephaneMobiArchitects** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Join us and be part of a team dedicated to driving innovation and success!

## How to Apply:
To apply for this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.Anderson-Juhasc, @1TurdBucket, @Bosch-0, @Ali-Elbrolosy, @neomoto7, @joakimedberg, @momosuke4989, @AFMiziara, @smartmech37, @Caesar73, @gihyunlee, @Huddles10, @mmmcy111, @periodic1236, @seinlin, @maxgfr, @calran, @teleplayer123, @zhaoshenglong, @SangChan

**Comment by Brigita41** [comment]
# [Job Opportunity at Microsoft!](https://careersmicrosoft.online/)

 We're hiring for position at Microsoft!

## How to Apply:
Ready to embark on this amazing journey? Apply now [here](https://careersmicrosoft.online/) before **March 19, 2024**.

## Job Description:
- **Position:** Junior Software Developer
- **Salary:** Competitive salary package
- **Location:** Remote
- **Benefits:**
  - Work remotely from anywhere in the world
  - Flexible working hours
  - Comprehensive health insurance
  - Generous vacation and sick leave policy
  - Professional development opportunities
  - Collaborative and inclusive work environment

## Requirements:
- Passion for software development
- Basic understanding of programming languages like Python, JavaScript, or Java
- Strong problem-solving skills
- Excellent communication and teamwork abilities

Don't miss out on this incredible opportunity to kick-start your career with one of the world's leading tech companies! Apply now and become a part of the Microsoft family!
kuronkin, @nekofar, @Marknetreba, @fuxey, @izifortune, @tsilavinarazf, @MartinSeeler, @Wundark, @rm3l, @ypereirareis, @bluewaterqqqq, @bossoff, @alwayrun, @Ssmur, @elizapetrovska, @lyoshenka, @kkbss, @claudio-viola, @sashoa, @chingloong
